variable vpc_id {}
variable my_ip {}
variable env-prefix {}
variable image_name {}
variable instance_type {}
variable avail_zone {}
variable path_to_public_key {}
variable subnet_cidr_block {}
variable vpc_cidr_block {}